### ISSUE TITLE
Different sequence length is used by default in training and test.py 

### ISSUE THREAD

**Issue by tastyminerals** [uds-lsv/TF-NNLM-TK#3]
I have noticed that in training TF-NNLM-TK uses `config_test.seq_length = 1` which is understandable. However, in `test.py` the args default value for sequence length is 5.
```python
parser.add_argument('--seq_length', type=int, default=5, 
help='word sequence length processed at each forward pass')
```

I wonder why. From my experience using sequence length > 1 for testing trained models only decreases the overall test sample accuracy. Can you please explain?

**Comment by michael-aloys** [comment]
Hi,

I can not tell you the original author's reason for that choice. But I think that it should not make any large difference during testing because we are keeping the LSTM state from the previous sequence. Therefore, we are not loosing any information (during prediction!). It should be equivalent to do 5 continuous sequences of length 1 (while keeping the LSTM state across sequences) or 1 sequence of length 5. During training, the case is different because the back-propagation stops at the sequence boundary.

Also, since we are just computing complexity, we are using the previous true words as input (as compared to using the last predicted word when generating actual text).

The small differences that do occur might be due to the splitting into batches during preprocessing. The current implementation of the preprocessing splits the data into blocks of batch_size * seq_length. Therefore, at the end, there is a small bit which might not be covered by a multiple of batch_size * seq_length. For PTB I measured differences < 1 point (in both directions), for larger datasets the difference should be smaller. Nevertheless, if seq_length is set to 1, this loosing of words should not occur.

Was my reasoning understandable and do you agree with it? I'd propose to set the default sequence length to 1 in all testing parts. A larger length might be more efficient (I do not have data on that), but can come with the mentioned problem of lost words in the end. Alternatively, the end could be padded.

**Comment by michael-aloys** [comment]
The seq_length for testing is now set to 1, adding a longer description to the parameter description in test.py. Feel free to open the ticket again if something is still unclear or you'd like to discuss this further.

**Comment by tastyminerals** [comment]
Thanks @michael-aloys for explanation, it does make sense to increase `seq_length` to reduce time of error computation. For prediction though, I'd leave it 1.
